name: "Buf Build"
on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
defaults:
  run:
    shell: bash
jobs:
  buf-build:
    name: "Run buf lint, breaking, build, and push"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: bufbuild/buf-setup-action@v1
        with:
          version: '1.6.0'
      # - uses: bufbuild/buf-lint-action@v1
      #   with:
      #     input: proto
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
      - uses: bufbuild/buf-breaking-action@v1
        with:
          input: proto
          against: https://github.com/${GITHUB_REPOSITORY}.git#branch=main
      - uses: bufbuild/buf-push-action@v1
        with:
          input: 'proto'
          buf_token: ${{ secrets.BUF_TOKEN }}
